### ISSUE TITLE
generate-graph fails 

### ISSUE THREAD

**Issue by AntiLopa** [FlorianPfisterer/vpc-flow-log-analysis#1]
I can't seem to generate the graph on win 10:

``` 
C:\git\vpc-flow-log-analysis-master>npm run generate-graph

> vpc-flow-log-analysis@1.0.0 generate-graph C:\git\vpc-flow-log-analysis-master
> ts-node ./graph-generator/index.ts

download log data from AWS s3: 1:34.392 (m:ss.mmm)
unzip log data: 1:59.968 (m:ss.mmm)
(node:22272) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'logs/log_2020-12-09T09:26:34.500Z.txt'
    at Object.openSync (fs.js:476:3)
    at mergeFiles (C:\git\vpc-flow-log-analysis-master\node_modules\merge-files\index.js:17:17)
    at C:\git\vpc-flow-log-analysis-master\graph-generator\s3-download.ts:70:38
    at step (C:\git\vpc-flow-log-analysis-master\graph-generator\s3-download.ts:33:23)
    at Object.next (C:\git\vpc-flow-log-analysis-master\graph-generator\s3-download.ts:14:53)
    at fulfilled (C:\git\vpc-flow-log-analysis-master\graph-generator\s3-download.ts:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

i was thinking it may have to do with how url is in win vs linux so I changed:
in s3-download.ts:
```
const mergedFileName = `logs/log_${new Date().toISOString()}.txt`;
```
to 
```
const mergedFileName = `logs\log_${new Date().toISOString()}.txt`;
```
and
```
const fullPath = `data/${object.Key}`;
```
to
```
const fullPath = `data\${object.Key}`;
```

in utils.ts:
```
    const folders = path.split('/');
    folders.pop();  // last element is file path
    const folderPath = folders.join('/');
```
to
```
    const folders = path.split('\\');
    folders.pop();  // last element is file path
    const folderPath = folders.join('\\');
```

and then I got:
```
C:\git\vpc-flow-log-analysis-master>npm run generate-graph

> vpc-flow-log-analysis@1.0.0 generate-graph C:\git\vpc-flow-log-analysis-master
> ts-node ./graph-generator/index.ts

(node:21376) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir ''
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21376) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21376) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Would love some guidance.

**Comment by FlorianPfisterer** [comment]
Has the `logs` directory been created by [this call](https://github.com/FlorianPfisterer/vpc-flow-log-analysis/blob/3c68c4bc1b3a15fff86e5824c826a3b2f220c042/graph-generator/s3-download.ts#L24)?

**Comment by AntiLopa** [comment]
The `logs` directory exists. not sure if by that call or other.

**Comment by AntiLopa** [comment]
tried to remove it - the directory is recreated with nothing inside (same error)

**Comment by FlorianPfisterer** [comment]
Hm, have you tried removing the `logs` folder prefix completely?

I.e., changing [this line](https://github.com/FlorianPfisterer/vpc-flow-log-analysis/blob/master/graph-generator/s3-download.ts#L23) to
```javascript
const mergedFileName = `log_${new Date().toISOString()}.txt`;
```

**Comment by AntiLopa** [comment]
same

```
 grant delete on fandalism.tblDistroBankWithdrawls  TO 'dkingestor_u'@'%';

```

**Comment by FlorianPfisterer** [comment]
Seems like you have kept your backslash Windows adjustments, can you reset them and then try again?

**Comment by AntiLopa** [comment]
I haven't.

This is what I have:
utils.ts:
````
    const folders = path.split('/');
    folders.pop();  // last element is file path
    const folderPath = folders.join('/');
````
s3-download.ts:
````
    const mergedFileName = `log_${new Date().toISOString()}.txt`;
````
and
````
        const fullPath = `data/${object.Key}`;

````

**Comment by FlorianPfisterer** [comment]
Hmm interesting, but it's the same error. I think we might need to skip [this step](https://github.com/FlorianPfisterer/vpc-flow-log-analysis/blob/master/graph-generator/s3-download.ts#L24) if we don't use a folder. Can you try that, please?

**Comment by AntiLopa** [comment]
````
download log data from AWS s3: 1:33.082 (m:ss.mmm)
unzip log data: 2:09.409 (m:ss.mmm)
(node:13616) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'log_2020-12-13T12:08:36.438Z.txt'
    at Object.openSync (fs.js:476:3)
    at mergeFiles (C:\git\vpc-flow-log-analysis-master\node_modules\merge-files\index.js:17:17)
    at C:\git\vpc-flow-log-analysis-master\graph-generator\s3-download.ts:68:38
    at step (C:\git\vpc-flow-log-analysis-master\graph-generator\s3-download.ts:33:23)
    at Object.next (C:\git\vpc-flow-log-analysis-master\graph-generator\s3-download.ts:14:53)
    at fulfilled (C:\git\vpc-flow-log-analysis-master\graph-generator\s3-download.ts:5:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13616) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13616) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by FlorianPfisterer** [comment]
Sorry, I can't reproduce it here. Might be a problem with the `merge-files` library on Windows / in your environment. I use Node version v15.3.0, maybe that's something to investigate.
